const mongoose = require('mongoose');
const { isOnlineMode } = require('../utils/paymentModes');
const Rank = require('../models/Rank');
const User = require('../models/User');
const settingService = require('./settingService');
const walletService = require('./walletService');
const rankService = require('./rankService');
const treeBuilderService = require('./treeBuilderService');

/**
 * Company's per-sqft share = Project's commissionPool minus the CAP already
 * assigned to the top-of-chain executive above this selling agent (the same
 * "Own" figure already computed by treeBuilderService.getCompanyTree()).
 * Preview-only — no wallet is credited for this.
 */
async function getCompanyRatePerSqft(sellingAgent, commissionPool) {
  const pool = Number(commissionPool) || 0;
  if (pool <= 0) return 0;

  const uplineChain = await treeBuilderService.getUplineChain(sellingAgent);
  const uplineIds = Object.values(uplineChain);
  const topLevelAgent = uplineIds.length > 0
    ? await User.findById(uplineIds[uplineIds.length - 1])
    : sellingAgent;

  const topLevelCap = Number(topLevelAgent?.slabPerSqft) || 0;
  return Math.max(pool - topLevelCap, 0);
}

/**
 * Process commission for a paid EMI. Mirrors CommissionService::processEmiCommission.
 *
 * Wrapped in a single Mongo transaction (like Laravel's DB::transaction) so
 * the seller credit, every upline credit, and the commissionProcessed flag
 * either all commit or all roll back — otherwise a mid-loop failure could
 * leave some agents paid, commissionProcessed still false, and a retry would
 * double-pay whoever already got credited.
 */
async function processEmiCommission(emi) {
  if (emi.commissionProcessed) return;

  const Booking = require('../models/Booking');
  const session = await mongoose.startSession();
  let sellingAgentForRankRefresh;

  try {
    await session.withTransaction(async () => {
      const booking = await Booking.findById(emi.booking).populate('agent').populate('agentRank').session(session);
      const sellingAgent = booking.agent;
      if (!sellingAgent) {
        emi.commissionProcessed = true;
        await emi.save({ session });
        return;
      }
      sellingAgentForRankRefresh = sellingAgent;
      const mode = emi.paymentMode || booking.paymentMode;
      // Always recompute sqftPortion fresh from the booking's own PLC data at
      // the moment of crediting, instead of trusting whatever was stored on
      // the EMI record when it was created. If an EMI was ever generated by
      // outdated logic (or edited by hand), this guarantees the ACTUAL money
      // credited is still correct — it doesn't inherit a stale value.
      const pricePerSqft = Number(booking.pricePerSqft) || 0;
      const totalAmount = Number(booking.totalAmount) || 0;
      const plcAmount = Number(booking.plcAmount) || 0;
      const baseAmount = Math.max(totalAmount - plcAmount, 0);
      const commissionRatio = totalAmount > 0 ? baseAmount / totalAmount : 1;
      const recomputedSqft =
        pricePerSqft > 0 ? Math.round(((Number(emi.amount) * commissionRatio) / pricePerSqft) * 100) / 100 : 0;
      const sqftPortion = recomputedSqft;
      if (Math.abs(recomputedSqft - Number(emi.sqftPortion)) > 0.01) {
        // Keep the stored field in sync too, so reports/exports (which read
        // emi.sqftPortion directly) always match what was actually credited.
        emi.sqftPortion = recomputedSqft;
      }

      const pointsType = isOnlineMode(mode) ? 'BV' : 'PV';
      const multiplier = await settingService.get(`${pointsType.toLowerCase()}_per_sqft`, 1.0);
      // 1. Seller commission based on snapshot rank at booking time
      let bookingRank = booking.agentRank;
      if (!bookingRank) {
        bookingRank = await Rank.findOne().sort({ sortOrder: 1 }).session(session);
      }

      const sellerPoints = pointsType === 'BV' ? Number(bookingRank?.bvPoints || 0) : Number(bookingRank?.pvPoints || 0);
      const cap = Number(booking.commissionCapPerSqft) || 0;
      const sellerRate = cap > 0 ? cap : sellerPoints * multiplier;
      const sellerEarning = sqftPortion * sellerRate;
      // Upline diff must be computed off the agent's DEFAULT slab, not any
      // self-given discount on this booking — otherwise a discount the agent
      // absorbs quietly inflates the upline's commission. The shortfall
      // between default and discounted cap goes to Company instead (see
      // previewCommissionForData's paidRatePerSqft), upline stays unaffected.
      const defaultSellerCap = Number(sellingAgent.slabPerSqft) || sellerRate;
      let previousCap = cap > 0 ? Math.max(cap, defaultSellerCap) : sellerRate;

      await walletService.credit(
        sellingAgent,
        sellerEarning,
        pointsType,
        'emi_commission',
        `EMI Commission - ${booking.bookingNumber} - Month ${emi.emiNumber}`,
        booking._id,
        emi._id,
        null,
        session,
        sqftPortion
      );

      // 2. Traverse upline chain for rank-difference commission
      const uplineChain = await treeBuilderService.getUplineChain(sellingAgent);
      const uplineCaps = booking.uplineCommissionCapsPerSqft || [];
      let previousRankPoints = sellerPoints;
      let uplineRowIndex = 0;

      for (const [level, uplineId] of Object.entries(uplineChain)) {
        const uplineAgent = await User.findById(uplineId).populate('rank').session(session);
        if (!uplineAgent) continue;

        const uplinePoints = await rankService.getAgentRankPoints(uplineAgent, pointsType);
        const difference = uplinePoints - previousRankPoints;

        if (difference > 0) {
          const rawCommission = sqftPortion * difference * multiplier;
          const uplineCap = Number(uplineCaps[uplineRowIndex]) || 0;
          const uplineRate = uplineCap > 0 ? Math.max(uplineCap - previousCap, 0) : difference * multiplier;
          const commission = sqftPortion * uplineRate;
          previousCap = uplineCap > 0 ? Math.max(uplineCap, previousCap) : previousCap;

          await walletService.credit(
            uplineAgent,
            commission,
            pointsType,
            'rank_difference',
            `Rank Difference Commission - ${booking.bookingNumber} - Month ${emi.emiNumber} - From ${sellingAgent.name}`,
            booking._id,
            emi._id,
            null,
            session
          );

          previousRankPoints = uplinePoints;
          uplineRowIndex++;
        }
      }

      // 3. Mark EMI as processed
      emi.commissionProcessed = true;
      await emi.save({ session });
    });
  } finally {
    session.endSession();
  }

  // 4. Rank/stats refresh — outside the transaction (matches Laravel, which
  // runs this after the DB::transaction closure completes).
  if (sellingAgentForRankRefresh) {
    await rankService.checkAndUpgradeRank(sellingAgentForRankRefresh);
  }
}

/**
 * Release commission for the Booking Deposit and Down Payment TOGETHER, as a
 * single combined payout — used only once the Down Payment has actually been
 * received. The Deposit's commission is intentionally never released on its
 * own while a Down Payment is expected on the booking; it stays held until
 * this method runs. Mirrors CommissionService::processCombinedDepositCommission.
 */
async function processCombinedDepositCommission(downPaymentEmi, depositEmi) {
  if (downPaymentEmi.commissionProcessed && depositEmi.commissionProcessed) return;

  const Booking = require('../models/Booking');
  const session = await mongoose.startSession();
  let sellingAgentForRankRefresh;

  try {
    await session.withTransaction(async () => {
      const booking = await Booking.findById(downPaymentEmi.booking).populate('agent').populate('agentRank').session(session);
      const sellingAgent = booking.agent;
      if (!sellingAgent) {
        downPaymentEmi.commissionProcessed = true;
        await downPaymentEmi.save({ session });
        depositEmi.commissionProcessed = true;
        await depositEmi.save({ session });
        return;
      }
      sellingAgentForRankRefresh = sellingAgent;
      const mode = downPaymentEmi.paymentMode || booking.paymentMode;
      // Same fix as processEmiCommission: recompute both legs fresh from the
      // booking's own PLC data at the moment of crediting, instead of
      // trusting stored sqftPortion values that could predate a formula fix.
      const pricePerSqft = Number(booking.pricePerSqft) || 0;
      const totalAmount = Number(booking.totalAmount) || 0;
      const plcAmount = Number(booking.plcAmount) || 0;
      const baseAmount = Math.max(totalAmount - plcAmount, 0);
      const commissionRatio = totalAmount > 0 ? baseAmount / totalAmount : 1;
      const recomputeSqft = (amount) =>
        pricePerSqft > 0 ? Math.round(((Number(amount) * commissionRatio) / pricePerSqft) * 100) / 100 : 0;
      const recomputedDownPaymentSqft = recomputeSqft(downPaymentEmi.amount);
      const recomputedDepositSqft = recomputeSqft(depositEmi.amount);
      const combinedSqft = recomputedDownPaymentSqft + recomputedDepositSqft;
      if (Math.abs(recomputedDownPaymentSqft - Number(downPaymentEmi.sqftPortion)) > 0.01) {
        downPaymentEmi.sqftPortion = recomputedDownPaymentSqft;
      }
      if (Math.abs(recomputedDepositSqft - Number(depositEmi.sqftPortion)) > 0.01) {
        depositEmi.sqftPortion = recomputedDepositSqft;
      }

      const pointsType = isOnlineMode(mode) ? 'BV' : 'PV';
      const multiplier = await settingService.get(`${pointsType.toLowerCase()}_per_sqft`, 1.0);
      let bookingRank = booking.agentRank;
      if (!bookingRank) {
        bookingRank = await Rank.findOne().sort({ sortOrder: 1 }).session(session);
      }

      const sellerPoints = pointsType === 'BV' ? Number(bookingRank?.bvPoints || 0) : Number(bookingRank?.pvPoints || 0);
      const cap = Number(booking.commissionCapPerSqft) || 0;
      const sellerRate = cap > 0 ? cap : sellerPoints * multiplier;
      const sellerEarning = combinedSqft * sellerRate;
      // Same fix as processEmiCommission: base the upline diff on the agent's
      // DEFAULT slab so a discount never passes through as extra upline
      // commission — the discount amount falls to Company instead.
      const defaultSellerCap = Number(sellingAgent.slabPerSqft) || sellerRate;
      let previousCap = cap > 0 ? Math.max(cap, defaultSellerCap) : sellerRate;

      await walletService.credit(
        sellingAgent,
        sellerEarning,
        pointsType,
        'deposit_commission',
        `Booking Deposit + Down Payment Commission - ${booking.bookingNumber}`,
        booking._id,
        downPaymentEmi._id,
        null,
        session,
        combinedSqft
      );

      const uplineChain = await treeBuilderService.getUplineChain(sellingAgent);
      const uplineCaps = booking.uplineCommissionCapsPerSqft || [];
      let previousRankPoints = sellerPoints;
      let uplineRowIndex = 0;

      for (const [level, uplineId] of Object.entries(uplineChain)) {
        const uplineAgent = await User.findById(uplineId).populate('rank').session(session);
        if (!uplineAgent) continue;

        const uplinePoints = await rankService.getAgentRankPoints(uplineAgent, pointsType);
        const difference = uplinePoints - previousRankPoints;

        if (difference > 0) {
          const rawCommission = combinedSqft * difference * multiplier;
          const uplineCap = Number(uplineCaps[uplineRowIndex]) || 0;
          const uplineRate = uplineCap > 0 ? Math.max(uplineCap - previousCap, 0) : difference * multiplier;
          const commission = combinedSqft * uplineRate;
          previousCap = uplineCap > 0 ? Math.max(uplineCap, previousCap) : previousCap;

          await walletService.credit(
            uplineAgent,
            commission,
            pointsType,
            'rank_difference',
            `Rank Difference (Deposit + Down Payment) - ${booking.bookingNumber} - From ${sellingAgent.name}`,
            booking._id,
            downPaymentEmi._id,
            null,
            session
          );

          previousRankPoints = uplinePoints;
          uplineRowIndex++;
        }
      }

      downPaymentEmi.commissionProcessed = true;
      await downPaymentEmi.save({ session });
      depositEmi.commissionProcessed = true;
      await depositEmi.save({ session });
    });
  } finally {
    session.endSession();
  }

  if (sellingAgentForRankRefresh) {
    await rankService.checkAndUpgradeRank(sellingAgentForRankRefresh);
  }
}

/**
 * Preview commission distribution from raw inputs (no saved booking needed).
 * Used both by the booking wizard's Commission step (before the booking exists)
 * and by previewCommission() below (for an already-saved booking).
 */
async function previewCommissionForData({
  agentId,
  agentRankId,
  pricePerSqft,
  emiAmount,
  emiMonths,
  paymentMode,
  commissionPool,
  companyRateOverride,
  sellerCapPerSqft = 0,
  uplineCapsPerSqft = [],
}) {
  const sellingAgent = await User.findById(agentId);
  if (!sellingAgent) throw new Error('Agent not found.');

  const preview = [];
  const mode = paymentMode;
  const sqftPortion = pricePerSqft > 0 ? Number(emiAmount) / pricePerSqft : 0;

  const pointsType = isOnlineMode(mode) ? 'BV' : 'PV';
  const multiplier = await settingService.get(`${pointsType.toLowerCase()}_per_sqft`, 1.0);

  let bookingRank = agentRankId ? await Rank.findById(agentRankId) : null;
  if (!bookingRank) {
    bookingRank = sellingAgent.rank ? await Rank.findById(sellingAgent.rank) : null;
  }
  if (!bookingRank) {
    bookingRank = await Rank.findOne().sort({ sortOrder: 1 });
  }

  const sellerPoints = pointsType === 'BV' ? Number(bookingRank?.bvPoints || 0) : Number(bookingRank?.pvPoints || 0);
  const rawSellerRatePerSqft = sellerPoints * multiplier;
  const sellerRatePerSqft = sellerCapPerSqft > 0 ? sellerCapPerSqft : rawSellerRatePerSqft;
  const sellerCommissionPerEmi = sqftPortion * sellerRatePerSqft;
  // Upline diff is computed off the agent's DEFAULT slab (sellingAgent.slabPerSqft),
  // never the discounted cap for this booking — so if the agent absorbs a
  // discount, the upline's incentive stays exactly as if there were no
  // discount. The gap between default and discounted cap simply isn't paid
  // out to seller or upline, so it flows to Company via paidRatePerSqft below.
  const defaultSellerCap = Number(sellingAgent.slabPerSqft) || sellerRatePerSqft;
  let previousCap = sellerCapPerSqft > 0 ? Math.max(sellerCapPerSqft, defaultSellerCap) : sellerRatePerSqft;

  preview.push({
    agent_id: sellingAgent._id,
    agent_name: sellingAgent.name,
    rank: bookingRank?.name || 'B.EX',
    role: 'Selling Agent',
    points_per_sf: sellerRatePerSqft,
    commission_per_emi: sellerCommissionPerEmi,
    total_commission: sellerCommissionPerEmi * emiMonths,
    default_cap_per_sqft: sellingAgent.slabPerSqft ?? 0,
    note: `Seller rank at booking time: ${bookingRank?.name || 'N/A'}`,
  });

  const uplineChain = await treeBuilderService.getUplineChain(sellingAgent);
  let previousRankPoints = sellerPoints;
  // Sum of what seller + upline actually earn, per sqft — Company's share is
  // whatever's left of the pool after this, not a disconnected formula.
  let paidRatePerSqft = sellerRatePerSqft;
  let uplineRowIndex = 0;

  for (const [level, uplineId] of Object.entries(uplineChain)) {
    const uplineAgent = await User.findById(uplineId).populate('rank');
    if (!uplineAgent) continue;

    const uplinePoints = await rankService.getAgentRankPoints(uplineAgent, pointsType);
    const difference = uplinePoints - previousRankPoints;

    if (difference > 0) {
      const rawUplineRatePerSqft = difference * multiplier;
      const uplineCap = Number(uplineCapsPerSqft[uplineRowIndex]) || 0;
      const uplineRatePerSqft = uplineCap > 0 ? Math.max(uplineCap - previousCap, 0) : rawUplineRatePerSqft;
      const commissionPerEmi = sqftPortion * uplineRatePerSqft;
      previousCap = uplineCap > 0 ? Math.max(uplineCap, previousCap) : previousCap;

      preview.push({
        agent_id: uplineAgent._id,
        agent_name: uplineAgent.name,
        rank: uplineAgent.rank?.name || 'B.EX',
        role: `Upline (${level})`,
        points_per_sf: uplineRatePerSqft,
        commission_per_emi: commissionPerEmi,
        total_commission: commissionPerEmi * emiMonths,
        default_cap_per_sqft: uplineAgent.slabPerSqft ?? 0,
      });

      paidRatePerSqft += uplineRatePerSqft;
      previousRankPoints = uplinePoints;
      uplineRowIndex++;
    }
  }

  // A saved booking passes its snapshotted rate (companyRateOverride); the
  // live wizard preview (before a booking exists) computes it fresh — Project
  // pool minus what seller + upline actually earn, a true leftover.
  const companyRate =
    companyRateOverride != null
      ? Number(companyRateOverride)
      : Math.max((Number(commissionPool) || 0) - paidRatePerSqft, 0);
  if (companyRate > 0) {
    const companyDisplayName = await settingService.get('site_title', 'Company');
    preview.push({
      agent_id: null,
      agent_name: companyDisplayName,
      rank: null,
      role: companyDisplayName,
      points_per_sf: companyRate,
      commission_per_emi: sqftPortion * companyRate,
      total_commission: sqftPortion * companyRate * emiMonths,
      note: 'Company share (Project pool minus what seller + upline actually earn)',
      isCompany: true,
    });
  }

  return preview;
}

/**
 * Preview commission for the one-time Booking Deposit + Down Payment portion
 * (no wallet writes). Mirrors what processCombinedDepositCommission() actually pays.
 */
async function previewDepositCommissionForData({ agentId, agentRankId, pricePerSqft, depositSqft, paymentMode, commissionPool, companyRateOverride, sellerCapPerSqft = 0, uplineCapsPerSqft = [] }) {
  const sellingAgent = await User.findById(agentId);
  if (!sellingAgent || depositSqft <= 0) return [];

  const preview = [];
  const pointsType = isOnlineMode(paymentMode) ? 'BV' : 'PV';
  const multiplier = await settingService.get(`${pointsType.toLowerCase()}_per_sqft`, 1.0);

  let bookingRank = agentRankId ? await Rank.findById(agentRankId) : null;
  if (!bookingRank) {
    bookingRank = sellingAgent.rank ? await Rank.findById(sellingAgent.rank) : null;
  }
  if (!bookingRank) {
    bookingRank = await Rank.findOne().sort({ sortOrder: 1 });
  }

  const sellerPoints = pointsType === 'BV' ? Number(bookingRank?.bvPoints || 0) : Number(bookingRank?.pvPoints || 0);
  const rawSellerRatePerSqft = sellerPoints * multiplier;
  const sellerRatePerSqft = sellerCapPerSqft > 0 ? sellerCapPerSqft : rawSellerRatePerSqft;
  preview.push({ agent_name: sellingAgent.name, commission: depositSqft * sellerRatePerSqft });

  // Same as previewCommissionForData: upline diff is computed off the
  // agent's DEFAULT slab, never the discounted cap — so the deposit portion
  // of a discount also flows to Company, not upline.
  const defaultSellerCap = Number(sellingAgent.slabPerSqft) || sellerRatePerSqft;
  let previousCap = sellerCapPerSqft > 0 ? Math.max(sellerCapPerSqft, defaultSellerCap) : sellerRatePerSqft;

  const uplineChain = await treeBuilderService.getUplineChain(sellingAgent);
  let previousRankPoints = sellerPoints;
  let uplineRowIndex = 0;

  for (const [level, uplineId] of Object.entries(uplineChain)) {
    const uplineAgent = await User.findById(uplineId).populate('rank');
    if (!uplineAgent) continue;

    const uplinePoints = await rankService.getAgentRankPoints(uplineAgent, pointsType);
    const difference = uplinePoints - previousRankPoints;

    if (difference > 0) {
      const rawUplineRatePerSqft = difference * multiplier;
      const uplineCap = Number(uplineCapsPerSqft[uplineRowIndex]) || 0;
      const uplineRatePerSqft = uplineCap > 0 ? Math.max(uplineCap - previousCap, 0) : rawUplineRatePerSqft;
      preview.push({ agent_name: uplineAgent.name, commission: depositSqft * uplineRatePerSqft });
      previousCap = uplineCap > 0 ? Math.max(uplineCap, previousCap) : previousCap;
      previousRankPoints = uplinePoints;
      uplineRowIndex++;
    }
  }

  const companyRate = companyRateOverride != null ? Number(companyRateOverride) : await getCompanyRatePerSqft(sellingAgent, commissionPool);
  if (companyRate > 0) {
    const companyDisplayName = await settingService.get('site_title', 'Company');
    preview.push({ agent_name: companyDisplayName, commission: depositSqft * companyRate, isCompany: true });
  }

  return preview;
}

/**
 * Preview commission distribution for an already-saved booking (no wallet writes).
 */
async function previewCommission(booking) {
  await booking.populate('agent');
  await booking.populate('agentRank');

  if (!booking.agent) {
    return { rows: [], summary: null };
  }

  // booking.pricePerSqft is the BASE rate only (excludes PLC), but the ₹
  // amounts we're about to convert to sqft (emiAmount, depositAmount,
  // registryAmount) already include PLC. Dividing PLC-inclusive money by a
  // PLC-exclusive rate silently inflates the resulting sqft (and therefore
  // the commission) by the PLC percentage. Use the true effective rate
  // (totalAmount / totalArea) instead, matching how the real EMI schedule's
  // sqftPortion was actually computed at booking creation.
  const totalArea = Number(booking.totalArea) || 0;
  const totalAmount = Number(booking.totalAmount) || 0;
  const pricePerSqft = totalArea > 0 ? totalAmount / totalArea : Number(booking.pricePerSqft) || 0;
  // Use the rate snapshotted at booking-creation time, not today's live Project
  // pool — a saved booking's commission must never shift when rates change later.
  const companyRateSnapshot = Number(booking.companyRatePerSqft) || 0;
  // The caps set on the booking wizard (and actually used by processEmiCommission
  // when EMIs get paid) must also drive this preview — otherwise the preview
  // silently falls back to rank-points × multiplier and disagrees with what
  // actually gets credited to wallets.
  const sellerCapPerSqft = Number(booking.commissionCapPerSqft) || 0;
  const uplineCapsPerSqft = booking.uplineCommissionCapsPerSqft || [];

  const Emi = require('../models/Emi');
  const scheduledEmis = await Emi.find({ booking: booking._id, emiNumber: { $gte: 1, $lte: booking.emiMonths } });
  const actualEmiAmount = scheduledEmis.length > 0
    ? scheduledEmis.reduce((s, e) => s + Number(e.amount || 0), 0) / scheduledEmis.length
    : Number(booking.emiAmount) || 0;

  const emiRows = await previewCommissionForData({
    agentId: booking.agent._id,
    agentRankId: booking.agentRank?._id || null,
    pricePerSqft,
    emiAmount: actualEmiAmount,
    emiMonths: booking.emiMonths,
    paymentMode: booking.paymentMode,
    companyRateOverride: companyRateSnapshot,
    sellerCapPerSqft,
    uplineCapsPerSqft,
  });

  // Booking Deposit + Down Payment are paid up front and their commission is
  // released together (see processCombinedDepositCommission) — separate from
  // the recurring per-EMI commission above.
  const depositAmount = Number(booking.bookingAmount || 0) + Number(booking.downPaymentAmount || 0);
  const depositSqft = pricePerSqft > 0 ? depositAmount / pricePerSqft : 0;

  const depositRows = await previewDepositCommissionForData({
    agentId: booking.agent._id,
    agentRankId: booking.agentRank?._id || null,
    pricePerSqft,
    depositSqft,
    paymentMode: booking.paymentMode,
    companyRateOverride: companyRateSnapshot,
    sellerCapPerSqft,
    uplineCapsPerSqft,
  });
  const depositMap = new Map(depositRows.map((d) => [d.agent_name, d.commission]));

  // Registry (the final settlement amount) generates real commission too —
  // processEmiCommission() runs for every paid Emi regardless of emiNumber,
  // including emiNumber 99 (Registry). This preview was previously missing
  // it entirely, so "Grand Total" always undercounted once Registry got paid.
  const registryAmount = Number(booking.registryAmount || 0);
  const registrySqft = pricePerSqft > 0 ? registryAmount / pricePerSqft : 0;
  const registryRows = await previewDepositCommissionForData({
    agentId: booking.agent._id,
    agentRankId: booking.agentRank?._id || null,
    pricePerSqft,
    depositSqft: registrySqft,
    paymentMode: booking.paymentMode,
    companyRateOverride: companyRateSnapshot,
    sellerCapPerSqft,
    uplineCapsPerSqft,
  });
  const registryMap = new Map(registryRows.map((r) => [r.agent_name, r.commission]));

  const rows = emiRows.map((row) => {
    const depositCommission = depositMap.get(row.agent_name) || 0;
    const registryCommission = registryMap.get(row.agent_name) || 0;
    return {
      ...row,
      deposit_commission: depositCommission,
      registry_commission: registryCommission,
      grand_total: depositCommission + registryCommission + row.total_commission,
    };
  });

  const totalDepositCommission = depositRows.reduce((s, d) => s + d.commission, 0);
  const totalRegistryCommission = registryRows.reduce((s, r) => s + r.commission, 0);
  const totalEmiCommission = emiRows.reduce((s, r) => s + r.total_commission, 0);

  return {
    rows,
    summary: {
      totalBookingAmount: Number(booking.totalAmount) || 0,
      bookingDepositAmount: depositAmount,
      registryAmount,
      totalDepositCommission,
      totalRegistryCommission,
      totalEmiCommission,
      grandTotalCommission: totalDepositCommission + totalRegistryCommission + totalEmiCommission,
    },
  };
}

module.exports = {
  processEmiCommission,
  processCombinedDepositCommission,
  previewCommission,
  previewCommissionForData,
  previewDepositCommissionForData,
  getCompanyRatePerSqft,
};